// Build a PDF report for a client export.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import type { ClientExportData } from "@/lib/data/client-export";

export function buildClientPdf(data: ClientExportData): Buffer {
  const { client, pl, runway, transactions } = data;
  const period = pl ? formatMonth(pl.period_month) : "Latest available";

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  doc.setFontSize(18);
  doc.text(client.client_name, 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(
    `${client.industry ?? "—"} · ${client.status} · ${period}`,
    14,
    28,
  );
  doc.setTextColor(0);

  doc.setFontSize(11);
  doc.text("Key metrics", 14, 38);

  const metrics: string[][] = [
    ["Annual revenue", formatGBP(client.annual_revenue)],
    ["Monthly revenue", formatGBP(pl?.revenue ?? null)],
    ["Gross profit", formatGBP(pl?.gross_profit ?? null)],
    ["EBITDA", formatGBP(pl?.ebitda ?? null)],
    [
      "EBITDA margin",
      pl ? `${pl.ebitda_margin_percent}%` : "—",
    ],
    ["Cash on hand", formatGBP(runway?.current_cash ?? null)],
    [
      "Net monthly cashflow",
      formatGBP(runway?.net_monthly_cashflow ?? null),
    ],
    [
      "Runway",
      runway ? formatRunway(runway.runway_category) : "—",
    ],
  ];

  autoTable(doc, {
    startY: 42,
    head: [["Metric", "Value"]],
    body: metrics,
    theme: "grid",
    headStyles: { fillColor: [45, 45, 45] },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 70 }, 1: { halign: "right" } },
  });

  const txStartY =
    (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY ?? 90;

  doc.setFontSize(11);
  doc.text(`Recent transactions (${transactions.length})`, 14, txStartY + 10);

  autoTable(doc, {
    startY: txStartY + 14,
    head: [["Date", "Category", "Type", "Amount"]],
    body: transactions.map((tx) => [
      formatShortDate(tx.transaction_date),
      tx.subcategory ? `${tx.category} / ${tx.subcategory}` : tx.category,
      tx.type,
      formatGBP(tx.amount),
    ]),
    theme: "striped",
    headStyles: { fillColor: [45, 45, 45] },
    styles: { fontSize: 8 },
    columnStyles: { 3: { halign: "right" } },
  });

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    `Generated by OnForm Internal Tool · ${new Date().toLocaleString("en-GB")}`,
    14,
    doc.internal.pageSize.height - 10,
  );

  return Buffer.from(doc.output("arraybuffer"));
}

const GBP = new Intl.NumberFormat("en-GB", {
  style: "currency",
  currency: "GBP",
  maximumFractionDigits: 0,
});

function formatGBP(value: number | null): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  return GBP.format(value);
}

function formatMonth(yyyymmdd: string): string {
  const d = new Date(yyyymmdd);
  if (Number.isNaN(d.getTime())) return yyyymmdd;
  return d.toLocaleString("en-GB", { month: "long", year: "numeric" });
}

function formatShortDate(yyyymmdd: string): string {
  const d = new Date(yyyymmdd);
  if (Number.isNaN(d.getTime())) return yyyymmdd;
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short" });
}

function formatRunway(category: string): string {
  return category
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/^\w/, (c) => c.toUpperCase());
}
